### ISSUE TITLE
model.predict returns different results.

### ISSUE THREAD

**Issue by onurgoker** [Dssdiego/ai_predict_sex#1]
I have a question regarding to the project. Each time I run the codeblock, I get different results from model.predict() function. In your code block, you have also quoted the following:

# The more close to 0, the more is a Male
# The more close to 1, the more is a Female

Could you please explain the reason of it?

**Comment by Dssdiego** [comment]
Hello @onurgoker. The reason why 0 is male and 1 is female is simply an abstraction. Since machine algorithms can only understand numbers, I chose 1 and 0 to make easier to read the results.

You can read more in the written article, here:
https://diegosseabra.files.wordpress.com/2018/04/trabalho1_mpeq.pdf
